global:
  scrape_interval: 1s 
  evaluation_interval: 1s # Evaluate rules every 1 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
 - "recording-rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "static-metrics"
    static_configs:
      - targets:
        - "metrics:80"
    metric_relabel_configs:
      - source_labels: ['__name__', 'lone']
        separator: ';'
        action: drop
        regex: 'apiserver_request_total;([^f]|f[^o]|fo[^o]).*'
#  - job_name: "node-exporter"
#    static_configs:
#      - targets:
#        - "node-exporter:9100"
